### ISSUE TITLE
golint warnings

### ISSUE THREAD

**Issue by soamvasani** [fission/fission#58]
Golint reports a bunch of warnings, mostly about missing comments.  We should clean up and remove unused exports [any tools for that?], and add comments where it makes sense.

https://goreportcard.com/report/github.com/platform9/fission#golint

**Comment by AlekSi** [comment]
> any tools for that?

https://github.com/dominikh/go-unused with `-exported` flag.

**Comment by vishal-biyani** [comment]
Latest report card: 
https://goreportcard.com/report/github.com/fission/fission

**Comment by ari-hacks** [comment]
👋🏾 I'd like to take this one.

**Comment by vishal-biyani** [comment]
@ari-hacks Thanks - please take it up & raise a PR when ready. Please let us know if you have any questions.

**Comment by ari-hacks** [comment]
@vishal-biyani and @soamvasani  I have a couple of questions: 

1. Can this issue be broken down into separate PRs because there is quite a bit? (For example a PR per file or per sub dir? )
2. I'm using [staticcheck](https://staticcheck.io/docs/#cli) the updated version of go-unused that was recommended above to check for unused exports, for exports not listed as unused is there a specific format for what the comments should be/look like?

**Comment by vishal-biyani** [comment]
@ari-hacks 

1. Absolutely, yes please - I think that will also make reviews easier.
2. Can you please give me an example, I am not super clear what do you mean here?

**Comment by ari-hacks** [comment]
@vishal-biyani, For example one warning reads:

Line 27: warning: exported type FakeFunction should have comment or be unexported (golint)

I was wondering what type of comment should precede that type. Or is this warning typical of all unused exports?

**Comment by vishal-biyani** [comment]
Oh ok, thanks @ari-hacks Yes it is a warning for all "Uncommented" exports. So if you can figure out easily, add comments, otherwise ignore. I will have one of the team members add comments once your PR is done.

**Comment by ari-hacks** [comment]
golint file reference: 

- [ ]  fission/pkg/fission-cli/cmd/timetrigger/list.go
- [ ] fission/pkg/controller/client/v1/fake/fake_function.go
- [ ] fission/pkg/controller/config.go
- [ ] fission/pkg/fission-cli/cmd/package/delete.go
- [ ] fission/pkg/storagesvc/storagesvc.go
- [ ] fission/pkg/executor/executortype/executortype.go
- [ ] fission/pkg/timer/main.go
- [x] fission/pkg/router/analytics.go (PR #1799)
- [ ] fission/pkg/fission-cli/cliwrapper/driver/cobra/helptemplate/templater.go
- [ ] fission/pkg/controller/client/v1/package.go
- [ ] fission/pkg/controller/client/v1/fake/fake_httptrigger.go
- [ ] fission/pkg/fission-cli/cmd/environment/command.go
- [ ] fission/environments/go/server.go
- [ ] fission/pkg/controller/client/v1/fake/fake_canaryconfig.go
- [ ] fission/pkg/controller/client/rest/client.go
- [ ] fission/pkg/fission-cli/cmd/kubewatch/delete.go
- [ ] fission/examples/message-queue/nats-streaming/mqtrigger/main.go
- [ ] fission/pkg/publisher/publisher.go
- [ ] fission/pkg/storagesvc/archivePruner.go
- [x] fission/pkg/fission-cli/cmd/support/command.go (PR #1799)
- [ ] fission/pkg/router/router.go
- [ ] fission/pkg/featureconfig/types.go
- [ ] fission/pkg/fission-cli/cliwrapper/cli/cli.go
- [ ] fission/pkg/controller/environmentApi.go
- [ ]  fission/pkg/controller/secretApi.go
- [ ] fission/pkg/controller/timeTriggerApi.go
- [ ] fission/pkg/fission-cli/cmd/package/list.go
- [ ] fission/pkg/error/network/error.go
- [x] fission/pkg/fission-cli/cmd/canaryconfig/command.go (PR #1799)
- [ ] fission/pkg/fission-cli/cmd/package/info.go
- [ ] fission/pkg/builder/builder.go
- [ ] fission/pkg/fission-cli/cliwrapper/driver/cobra/cobra.go
- [ ] fission/pkg/fission-cli/cmd/spec/destroy.go
- [ ] fission/pkg/mqtrigger/messageQueue/azurequeuestorage/asq.go
- [ ] fission/pkg/controller/client/v1/fake/fake_package.go

**Comment by ari-hacks** [comment]
Hey @vishal-biyani, this is what I'm thinking to organize these PRs. Let me know if this works.

I also need to spend a little more time with the codebase and Go to make meaningful comments, in the meantime, maybe more people can jump in here as well 🙂

**Comment by vishal-biyani** [comment]
Hey @ari-hacks - this is wonderful and thanks for giving it a nice structure. I really appreciate your work on this!

**Comment by avats-dev** [comment]
@vishal-biyani @ari-hacks Can I also work on fixing some of the files as mentioned in above list? I would love to contribute.

**Comment by vishal-biyani** [comment]
Hey @avats-dev thanks a lot! I am ok as long as it works for @ari-hacks and you two can coordinate!

**Comment by ari-hacks** [comment]
@avats-dev yes, absolutely! Please add the PR number next to the files you update for consistency.🙂

**Comment by avats-dev** [comment]
Thanks @ari-hacks and @vishal-biyani , I'll get started and will keep you updated.

**Comment by avats-dev** [comment]
Thanks @ari-hacks and @vishal-biyani , I'll get started and will keep you updated.

**Comment by ShajithaMohammed** [comment]
> Hey @vishal-biyani, this is what I'm thinking to organize these PRs. Let me know if this works.
> 
> I also need to spend a little more time with the codebase and Go to make meaningful comments, in the meantime, maybe more people can jump in here as well 🙂

@ari-hacks @vishal-biyani I can help with fixing some files!

**Comment by ari-hacks** [comment]
@avats-dev and @ShajithaMohammed please note which files you are working on so there are no conflicts, thanks!

**Comment by sanketsudake** [comment]
We are using golangci-lint now. It effectively adds a couple of linters. We plan to add more linters to the code. The current set of linters and fixes are good enough for now. 

Closing this issue as its very generic will open issues for specific linter fixes in context golangci-lint linters.
